### ISSUE TITLE
[Bug]: 标题和正文不是同一个语言

### ISSUE THREAD

**Issue by uzcool** [rss-translator/RSS-Translator#28]
### 版本号 | Version

2024.02.26

### System

Others

### 请描述这个Bug | Describe the bug

https://repack.me/rss.xml 

比如说这种订阅..标题是英文的,但是全文是俄语的..

然后就会出现翻译了全文没标题 要不就是只能翻译标题全文没翻译 有办法解决吗?
![1](https://github.com/rss-translator/RSS-Translator/assets/38136975/4e2cdb61-7640-420e-812e-a7737115f593)
![2](https://github.com/rss-translator/RSS-Translator/assets/38136975/3d94aaf5-05d0-4edc-8a58-746e484bd0a2)

**Comment by versun** [comment]
没有翻译是因为翻译失败了，所以使用原文，这种情况比较多出现在免费的翻译引擎上，比如Google web、deeplx和gemini上。
建议使用收费的翻译引擎。
同时，标题没有翻译是一个已知bug，会尽快修复
