### ISSUE TITLE
[Bug]: 翻译后的内容格式变得混乱

### ISSUE THREAD

**Issue by hnboy2005** [rss-translator/RSS-Translator#29]
### 版本号 | Version

2024.3.12

### System

Others

### 请描述这个Bug | Describe the bug

源Feed地址 https://www.visualcapitalist.com/feed/
翻译后的地址 http://192.3.53.96:8000/rss/edba34511fb35f70bc50e2374464b6be_chinese_simplified
网页内容格式打乱了, 源Feed里可与查看到图片等, 在翻译后的Feed里看不到图片了 (使用InoReader订阅)
换其他的源也有类似的问题

<img width="610" alt="iShot_2024-03-14_11 00 40" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/fc2f6bf7-c914-4c72-aa26-bc60676872c2">
<img width="666" alt="iShot_2024-03-14_11 00 32" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/90474349-75e0-4816-ad6c-53cf454fe495">

**Comment by versun** [comment]
感谢反馈，正在处理这个问题

**Comment by versun** [comment]
@hnboy2005 可以显示图片了
