### ISSUE TITLE
[Bug]: 翻译后的结果相比原始来源多了一些内容

### ISSUE THREAD

**Issue by hnboy2005** [rss-translator/RSS-Translator#35]
### 版本号 | Version

2024.3.14_1

### 请描述这个Bug | Describe the bug

来源: https://www.inoreader.com/stream/user/1005923757/tag/Bloomberg

<img width="1896" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/612c9f88-a26d-4938-ad88-e6ddc5a11f4c">

**Comment by versun** [comment]
感谢反馈，今天应该能修复

**Comment by versun** [comment]
这个问题之前已经修复了，麻烦升级到2024.3.22_1版本哈
