### ISSUE TITLE
[Feature]: 增加图片翻译开关

### ISSUE THREAD

**Issue by hnboy2005** [rss-translator/RSS-Translator#40]
### 概述 | Summary

有些英文RSS的源里内嵌的图片也是英文的图表,是否有机会做一个开关来决定是否启用图片翻译
目前已经有一些图片翻译插件可以在网页中实现类似效果(例如https://chrome.google.com/webstore/detail/pbhpcbdjngblklnibanbkgkogjmbjeoe ; 
https://chrome.google.com/webstore/detail/dgeiaiglmhdhajbpfbmajaajdlfdinpi )
但是在移动设备上使用就不太方便,而且操作也比较繁琐.
 
<img width="663" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/59408bfc-395a-4425-a3cf-dc1f73a3a0c6">

**Comment by versun** [comment]
这个功能涉及到OCR，会占用很多系统资源，所以暂时不会添加哈
