### ISSUE TITLE
建议 Google Translate 改用 get 版本的免费高并发引擎

### ISSUE THREAD

**Issue by zj1123581321** [rss-translator/RSS-Translator#50]
### 概述 | Summary

目前服务使用的 Google translate api 看上去是有频次限制的，容易触发频次上限 。

建议改用下方的 API，这也是沉浸式翻译等软件所使用的 google 翻译 api，免费高并发，轻松翻译近万文章。

# 使用 Google Translate API 翻译文本
def translate_text_google(text, target_language):
    encoded_text = urlencode({'': text})[1:]
    url = f"https://translate.googleapis.com/translate_a/single?dt=t&dt=bd&dt=qc&dt=rm&client=gtx&sl=auto&tl={target_language}&hl=en-US&dj=1&q={encoded_text}&tk=574558.574558"
    response = requests.get(url)
    if response.status_code == 200:
        response_data = response.json()
        translation = ''.join([sentence['trans'] for sentence in response_data.get('sentences', []) if 'trans' in sentence])
        return translation
    else:
        raise Exception(f"Error: {response.status_code} \n\n{response.text}")

**Comment by versun** [comment]
哈哈， 目前用的就是这个方法，沉浸式翻译能大批量翻译，主要是因为使用了真实的客户端浏览器+真实IP，而RSS翻译器基本上都是用服务器的IP和伪造的浏览器指纹，所以比较容易被限制。
建议使用收费服务哈，更稳定

**Comment by versun** [comment]
已改用single端点，感谢建议
