### ISSUE TITLE
[Feature]: 希望可以在CentOS上运行

### ISSUE THREAD

**Issue by YorkeSun** [rss-translator/RSS-Translator#53]
### 概述 | Summary

如题希望可以在centos上运行

**Comment by versun** [comment]
@YorkeSun 
centos默认自带的python版本太低了哈，不能使用一键安装，只能使用docker安装了

**Comment by YorkeSun** [comment]
给centos 7.9安装了python 3.11但依然无法一键安装。代码小白正在排查原因

**Comment by versun** [comment]
根据我之前的测试，7.9虽然安装了python 3.11，但还需要更新很多第三方依赖，挺麻烦的。
你可以发下报错信息
