### ISSUE TITLE
[Bug]: 翻译标题只有时间

### ISSUE THREAD

**Issue by rader124124** [rss-translator/RSS-Translator#64]
### 版本号 | Version

2024.5.1

### System

Others

### 请描述这个Bug | Describe the bug

<img width="672" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/68490435/005d190b-0035-47d3-8d4f-40f794302e52">

**Comment by versun** [comment]
用的什么翻译引擎呢？谷歌web吗？

**Comment by rader124124** [comment]
> 用的什么翻译引擎呢？谷歌web吗？ 源地址也发下，方便测试
你好，使用的是OpenAI GPT3.5，
地址 https://rsshub.app/reuters/world/china

**Comment by versun** [comment]
我这边测试了正常，你看下你的api额度还有吗？

**Comment by rader124124** [comment]
> 我这边测试了正常，你看下你的api额度还有吗？

全部是正常的，不知道是不是使用自定义api地址的原因，（可以使用 https://api.v3.cm/ 试试，有免费额度）

**Comment by versun** [comment]
可以提供下data/app.log日志吗，我看下日志是否有报错

**Comment by versun** [comment]
看了下你提供的网址，已经没有提供免费额度了

**Comment by rader124124** [comment]
> 可以提供下data/app.log日志吗，我看下日志是否有报错
ERROR 2024-05-11 05:14:27,487 Translator->Error code: 400 - {'error': {'message': 'max_tokens is too large: 10000. This model supports at most 4096 completion tokens, whereas you provided 10000.    (request id: 20240511131427150044930KanSUb9p)', 'type': 'new_api_error',
感谢。查看日志找到问题了

**Comment by versun** [comment]
好的，记得升级到5.10版本，旧版本有重复翻译的bug
