### ISSUE TITLE
[Bug]: Token使用异常

### ISSUE THREAD

**Issue by hnboy2005** [rss-translator/RSS-Translator#67]
### 版本号 | Version

2024.4.28.1

### 源地址 | Feed URL

https://staysaasy.com/feed.xml

### 请描述这个Bug | Describe the bug

在24小时内 原始Feed只更新了1篇文章, 英文单词数量大概在1700字左右
但是这个Feed的花费Token数增长了700万左右,是哪里有问题?
翻译后的Feed  http://192.3.53.96:8000/rss/staysaasy
<img width="1369" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/dc408339-6a2f-4ad9-8dd0-7d817018ce90">

**Comment by hnboy2005** [comment]
每天花费3700万的Token 钱包吃不消 😭
翻译用的是Google Translate(Web) 免费的
总结摘要用的是 OpenRouter家的meta-llama/llama-3-8b-instruct

<img width="1434" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/e046e546-2058-4227-9d65-4aeddb59e11c">

**Comment by versun** [comment]
应该是重复翻译的问题，建议更新到2024.5.10版本

**Comment by hnboy2005** [comment]
好像还是有问题 已升级到 2024.5.10 
今天统计了下  24小时的Token使用量还是 3400万左右的Token
发现个问题 举例 stratechery这个Feed在4/29后都没有更新文章
但是每天的Token增量在560万左右
原始Feed: https://rss.stratechery.passport.online/feed/rss/X3PGXFFzQnCGwZxNTXn9rs
翻译后的Feed: http://192.3.53.96:8000/rss/stratechery

<img width="403" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/6138b6ac-901b-4b2b-80c6-dfabe6d0f90f">

<img width="411" alt="image" src="https://github.com/rss-translator/RSS-Translator/assets/3166227/247c7c1f-e3ec-4a47-8da8-5221d971eee7">

**Comment by versun** [comment]
已修复，请升级到2024.5.13
