### ISSUE TITLE
[Feature]: 可否加个RSS源条目强制按时间重新排序后再翻译

### ISSUE THREAD

**Issue by tjsky** [rss-translator/RSS-Translator#79]
### 概述 | Summary

因为有些不太规范的源（比如[t-online.de](https://www.t-online.de/feed.rss)、[BBC](https://feeds.bbci.co.uk/news/rss.xml)）他的条目不是最新更新的条目在最上边，而是随机分布的。（貌似他们是将自己首页内容半同步的转换为RSS）
![_20240528155150](https://github.com/rss-translator/RSS-Translator/assets/7272911/a994a1d1-318e-4b0d-8f2a-65bcf4805c7d)

大部分RSS阅读器会自动纠正这个问题，将得到的条目自动按照时间排序后显示。（就如同下图所示那样）
但是对于翻译rss-translator，就造成一个很麻烦的问题：
除非我选择把70个条目全翻译了，不然只翻译前20个的时候得到的翻译源，总是有最新更新的条目在20个之后而不翻译（就如同下图所示那样）。
但每次都翻译70个条目需要的翻译消耗也太大了点。
![_20240528155501](https://github.com/rss-translator/RSS-Translator/assets/7272911/082d4eeb-a39a-4514-b618-4aa07f72695c)

**Comment by versun** [comment]
我也发现这个问题了，但其实影响不大，理由如下：
1. 原始源时间错乱，大部分是因为旧文章被更新了，所以插入到了新时间线里。
2. 选择翻译70条，只在第一次翻译时比较费钱，之后都是增量翻译，并不是每次都翻译70条，因为翻译都有缓存的。
anyway，下个版本会尝试解决这个问题
