### ISSUE TITLE
[Bug]: 更新后oneapi无法使用

### ISSUE THREAD

**Issue by Fan-Bob** [rss-translator/RSS-Translator#88]
### 版本号 | Version

6.20

### 源地址 | Feed URL

rss-translator

### 请描述这个Bug | Describe the bug

oneapi无论如何无法正常调用

**Comment by versun** [comment]
我刚刚自己搭了个oneapi，也是用的IP：port格式，最新版本下也能用的，可能需要检查下你的网络/防火墙设置
