### ISSUE TITLE
[Feature]: Ollama support

### ISSUE THREAD

**Issue by boyiechen** [rss-translator/RSS-Translator#90]
### 概述 | Summary

First of all, thanks for the great project! I think it manages translated RSS feed pretty well, and I am using it for my every day life.

I also wonder if Ollama would be supported as one of the translators. I was also trying to replace the URI input in the OpenAI translator field, but it seems that Ollama does not come with an API key authentication process. Thus, I cannot simply use the existing field to use Ollama.

It would be great if this project had Ollama integration! And thanks for the hard work for everything you have done in this project.

**Comment by versun** [comment]
Hi @boyiechen 
Thank you for your interest in integrating Ollama with RSS Translator! I'm happy to inform you that Ollama does support the OpenAI API interface. Here are a few key points:

1. You can use the existing OpenAI translator field to connect to Ollama.
2. For the API key, you can enter any value - Ollama will ignore it. A placeholder like "ollama" works fine.
3. If using Docker for both RSS Translator and Ollama, you may need to create a Docker network so the containers can communicate.

To set it up:
1. Use the OpenAI translator field in RSS Translator.
2. Set the API endpoint to your Ollama instance (e.g. http://ollama:11434/v1 if using Docker networking).
3. Enter any value for the API key.

Let me know if you need any other help getting it configured!

**Comment by boyiechen** [comment]
@versun Thanks for the quick reply! 

It's terrific great news to me to know that Ollama does work on this project!
I have been working on bypassing the API key, and it seems like I just need to put whatever placeholder, and it works 👍 


I am testing with different models right now. The basic "llama3" model seems to work, while other third-party models would probably need to be specified more clearly in the model selection field. I will update my findings and hopefully contribute to part of the documentation to make the project much better! 

Once again, I would like to thank you for the great project!
