### ISSUE TITLE
[Bug]:  翻译后无法用TTRSS订阅

### ISSUE THREAD

**Issue by valuex** [rss-translator/RSS-Translator#97]
### 版本号 | Version

2024.8.30

### 请描述这个Bug | Describe the bug

源：https://www.[nature.com/nmat.rss](https://www.nature.com/nmat.rss)

翻译后的效果：
![image](https://github.com/user-attachments/assets/ed3aac1f-f6e7-4dd8-a3d3-71c1cf432fa5)
翻译后无法在ttrss 中订阅，帮忙看看如何解决，谢谢。

tiny tiny rss 订阅错误消息
![image](https://github.com/user-attachments/assets/e39d9c04-4222-4632-b079-5142bbb8b1c3)

PS: 感谢作者大大开发的用心开发~

**Comment by versun** [comment]
哈喽 @valuex 
这个是你的本地网络问题哈，ttrss和翻译器网络不通
你可以在demo站点上随便拿个订阅地址放在TTRSS里面看能不能订阅。

还解决不了的话，你可以在tg群里发下哈，群里回复比较快

**Comment by valuex** [comment]
谢谢回复。的确是服务不通，把rss_tanslate的端口号加入到ttrss中的allow_ports后就行了。
