### ISSUE TITLE
[Others]: 希望增加失败后不要停止下次更新的选项

### ISSUE THREAD

**Issue by Limour-dev** [rss-translator/RSS-Translator#98]
### 概述 | Summary

对接rsshub时某些接口可能临时失效，一段时间后会自动恢复，而本项目在某次验证失败后会暂停解析，需要手动强制更新才能恢复。

希望可以在添加原始源时增加一个忽略验证失败的选项，后续无论源是否解析错误，都会持续按照设定的周期更新源。

**Comment by versun** [comment]
@Limour-dev 
默认就是会按设定的周期持续尝试更新源的，无论是否验证失败。
你可以加下tg群，或者私聊我，发送下data/app.log日志，我排查下。

对了，目前最新版本是2024.8.30，如果是旧版本，可以更新下再观察一段时间

**Comment by Limour-dev** [comment]
> @Limour-dev 默认就是会按设定的周期持续尝试更新源的，无论是否验证失败。 你可以加下tg群，或者tg私聊我，发送下data/app.log日志，我排查下。
> 
> 对了，目前最新版本是2024.8.30，如果是旧版本，可以更新下再观察一段时间

哦，是旧版本，我更新后再观察观察，感谢~
